contributor:
  description: The amazing design team
  team_sync_ignored: true
  members:
  - name: Dan Ta
    github: dantatata
newteam:
  description: A new team
  members:
  - name: Dan Ta
    github: dantaclaus
dansteam:
  description: Dantatata's team
  members:
  - name: Dan Ta
    github: dantatata
