name: github-mirroring

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mirrorrepo:
    if: ${{ !contains(github.repository, 'automated-workflow-create-test') }}
    runs-on: ubuntu-latest  
    # The type of runner that the job will run on
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          # SSH private key for ssh connection to the target repository
          ssh_private_key: ${{ secrets.TARGET_SSH_PRIVATE_KEY }}
          # Target url
          target_repo_url: git@github.com:danta-org/automated-workflow-create-test.git